const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.body, __VLS_intrinsicElements.body)({ ...{ class: ("flex flex-col") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col justify-center px-6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative w-full h-auto md:h-screen bg-cover bg-center") }, ...{ style: ({}) }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("flex justify-center p-4 items-center text-xl md:text-2xl font-medium bg-gray-700/80 text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col w-full text-black z-100 relative bg-white/70 p-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:flex-row md:space-x-10 space-y-4 md:space-y-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("flex flex-col md:flex-row items-center rounded-xl p-4 bg-white shadow-md flex-grow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../../assets/icons/naprawa1.png"), ...{ class: ("w-16 h-16 md:w-24 md:h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col space-y-3 ml-0 md:ml-4 mt-4 md:mt-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-row justify-between w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-lg md:text-xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-lg md:text-xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-800 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("flex flex-col md:flex-row items-center rounded-xl p-4 bg-white shadow-md flex-grow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../../assets/icons/konwersja1.png"), ...{ class: ("w-16 h-16 md:w-24 md:h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col space-y-3 ml-0 md:ml-4 mt-4 md:mt-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-row justify-between w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-lg md:text-xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-lg md:text-xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-800 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.strong, __VLS_intrinsicElements.strong)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.hr, __VLS_intrinsicElements.hr)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("flex flex-col md:flex-row items-center rounded-xl p-4 bg-white shadow-md flex-grow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../../assets/icons/rent1.png"), ...{ class: ("w-16 h-16 md:w-24 md:h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col space-y-3 ml-0 md:ml-4 mt-4 md:mt-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-row justify-between w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-lg md:text-xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-lg md:text-xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-800 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.hr, __VLS_intrinsicElements.hr)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.strong, __VLS_intrinsicElements.strong)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.h1, __VLS_intrinsicElements.h1)({ ...{ class: ("flex justify-center p-4 items-center text-xl md:text-2xl font-medium bg-gray-700/80 text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col w-full text-black z-100 relative bg-white/70 p-4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:flex-row md:space-x-10 justify-between space-y-4 md:space-y-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("flex flex-col md:flex-row items-center rounded-xl p-4 bg-white shadow-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../../assets/icons/battery.png"), ...{ class: ("w-16 h-16 md:w-24 md:h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col space-y-3 ml-0 md:ml-4 mt-4 md:mt-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-row justify-between w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-lg md:text-xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-lg md:text-xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.hr, __VLS_intrinsicElements.hr)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("flex flex-col md:flex-row items-center rounded-xl p-4 bg-white shadow-md") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../../assets/icons/compose.png"), ...{ class: ("w-16 h-16 md:w-24 md:h-24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col space-y-3 ml-0 md:ml-4 mt-4 md:mt-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-row justify-between w-full") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-lg md:text-xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-lg md:text-xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.hr, __VLS_intrinsicElements.hr)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-gray-700 text-sm md:text-base") }, });
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['justify-center'];
    __VLS_styleScopedClasses['px-6'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['md:h-screen'];
    __VLS_styleScopedClasses['bg-cover'];
    __VLS_styleScopedClasses['bg-center'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['justify-center'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['bg-gray-700/80'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-black'];
    __VLS_styleScopedClasses['z-100'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['bg-white/70'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['md:space-x-10'];
    __VLS_styleScopedClasses['space-y-4'];
    __VLS_styleScopedClasses['md:space-y-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['rounded-xl'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['bg-white'];
    __VLS_styleScopedClasses['shadow-md'];
    __VLS_styleScopedClasses['flex-grow'];
    __VLS_styleScopedClasses['w-16'];
    __VLS_styleScopedClasses['h-16'];
    __VLS_styleScopedClasses['md:w-24'];
    __VLS_styleScopedClasses['md:h-24'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['space-y-3'];
    __VLS_styleScopedClasses['ml-0'];
    __VLS_styleScopedClasses['md:ml-4'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['text-gray-800'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['rounded-xl'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['bg-white'];
    __VLS_styleScopedClasses['shadow-md'];
    __VLS_styleScopedClasses['flex-grow'];
    __VLS_styleScopedClasses['w-16'];
    __VLS_styleScopedClasses['h-16'];
    __VLS_styleScopedClasses['md:w-24'];
    __VLS_styleScopedClasses['md:h-24'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['space-y-3'];
    __VLS_styleScopedClasses['ml-0'];
    __VLS_styleScopedClasses['md:ml-4'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['text-gray-800'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['rounded-xl'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['bg-white'];
    __VLS_styleScopedClasses['shadow-md'];
    __VLS_styleScopedClasses['flex-grow'];
    __VLS_styleScopedClasses['w-16'];
    __VLS_styleScopedClasses['h-16'];
    __VLS_styleScopedClasses['md:w-24'];
    __VLS_styleScopedClasses['md:h-24'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['space-y-3'];
    __VLS_styleScopedClasses['ml-0'];
    __VLS_styleScopedClasses['md:ml-4'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['text-gray-800'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['justify-center'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['bg-gray-700/80'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-black'];
    __VLS_styleScopedClasses['z-100'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['bg-white/70'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['md:space-x-10'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['space-y-4'];
    __VLS_styleScopedClasses['md:space-y-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['rounded-xl'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['bg-white'];
    __VLS_styleScopedClasses['shadow-md'];
    __VLS_styleScopedClasses['w-16'];
    __VLS_styleScopedClasses['h-16'];
    __VLS_styleScopedClasses['md:w-24'];
    __VLS_styleScopedClasses['md:h-24'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['space-y-3'];
    __VLS_styleScopedClasses['ml-0'];
    __VLS_styleScopedClasses['md:ml-4'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['rounded-xl'];
    __VLS_styleScopedClasses['p-4'];
    __VLS_styleScopedClasses['bg-white'];
    __VLS_styleScopedClasses['shadow-md'];
    __VLS_styleScopedClasses['w-16'];
    __VLS_styleScopedClasses['h-16'];
    __VLS_styleScopedClasses['md:w-24'];
    __VLS_styleScopedClasses['md:h-24'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['space-y-3'];
    __VLS_styleScopedClasses['ml-0'];
    __VLS_styleScopedClasses['md:ml-4'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-0'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-lg'];
    __VLS_styleScopedClasses['md:text-xl'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    __VLS_styleScopedClasses['text-gray-700'];
    __VLS_styleScopedClasses['text-sm'];
    __VLS_styleScopedClasses['md:text-base'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
;
//# sourceMappingURL=BodyView.vue.js.map